import keyMirror from 'key-mirror'

export const ACTION_TYPES = keyMirror({
  CLEAN_APPOINTMENT_LIST_ERROR: null,
  CLEAN_APPOINTMENT_LIST: null,
  CLEAN_APPOINTMENT_LIST_FILTER: null,
  CHANGE_APPOINTMENT_LIST_FILTER: null,
  CHANGE_APPOINTMENT_LIST_FILTER_FIELD: null,
  LOAD_APPOINTMENT_LIST_REQUEST: null,
  LOAD_APPOINTMENT_LIST_SUCCESS: null,
  LOAD_APPOINTMENT_LIST_FAILURE: null,

  CLEAR_APPOINTMENT_STATUS_LIST: null,
  CLEAR_APPOINTMENT_STATUS_LIST_ERROR: null,
  LOAD_APPOINTMENT_STATUS_LIST_REQUEST: null,
  LOAD_APPOINTMENT_STATUS_LIST_SUCCESS: null,
  LOAD_APPOINTMENT_STATUS_LIST_FAILURE: null
})